version: '3'
services:
  app:
    build: ./
#    restart: always
    command: sh -c "yarn && yarn run dev"
#    command: sh -c "yarn && yarn run load && yarn run dev"
#    command: sh -c "yarn test"
    environment:
      - NODE_ENV=development
      - PORT=8080
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    working_dir: /user/src/app
    volumes:
      - ./:/user/src/app:cached
#      - /user/src/app/node_modules
#  app-test:
#    command: sh -c "npm i && npm run test"
#    environment:
#      - NODE_ENV=development
#      - PORT=8080
#    depends_on:
#      - redis
#      - postgres
